# Generated by Django 5.0 on 2023-12-24 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_employee_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.department",
            ),
            preserve_default=False,
        ),
    ]
