# Generated by Django 5.0 on 2023-12-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_department_title_alter_employee_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
